export const LOAD_NEW_FILE = 'LOAD_NEW_FILE';
export const LOAD_NEW_FILE_REQUEST = 'LOAD_NEW_FILE_REQUEST';
export const LOAD_NEW_FILE_FAILURE = 'LOAD_NEW_FILE_FAILURE';

export const CALCULATE_ELO = 'CALCULATE_ELO';
export const CALCULATE_ELO_REQUEST = 'CALCULATE_ELO_REQUEST';
export const CALCULATE_ELO_FAILURE = 'CALCULATE_ELO_FAILURE';
